@api = http://localhost:3000/tasks

GET {{api}}

###
GET {{api}}/1

###
GET {{api}}/count

###
POST {{api}}
Content-Type: application/json

{
    "title":"I must create web app",
    "description":"With tabine"
}

###
DELETE {{api}}/4

###
PUT {{api}}/1
Content-Type: application/json

{
    "title": "I have to dinner"
}